# Copyright 2024-2025 HNU-ESNL: Guoqi Xie, Chenglai Xiong, Xingyu Hu and etc.
# Copyright 2024-2025 openEuler SIG-Zephyr
# SPDX-License-Identifier: Apache-2.0

# ZVM
CONFIG_ZVM=y
CONFIG_ZVM_DEBUG_LOG_INFO=y
CONFIG_ZVM_SMP_DEBUG_INFO=n
CONFIG_MAX_VM_NUM=10
CONFIG_MAX_VCPU_PER_VM=4
CONFIG_VM_DTB_FILE_INPUT=y
CONFIG_KERNEL_BIN_NAME="zvm_host"

# console
CONFIG_CONSOLE=y
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETLINE=y
CONFIG_UART_CONSOLE=y
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=4096
# log
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_ASSERT=y

# c lib
CONFIG_MINIMAL_LIBC=y
CONFIG_MINIMAL_LIBC_RAND=y
CONFIG_MINIMAL_LIBC_NON_REENTRANT_FUNCTIONS=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=4096
CONFIG_GETOPT_LONG=y
CONFIG_POSIX_C_LIB_EXT=y

#shell
CONFIG_SHELL=y
CONFIG_SHELL_GETOPT=y
CONFIG_SHELL_THREAD_PRIORITY_OVERRIDE=y
CONFIG_SHELL_THREAD_PRIORITY=4
CONFIG_SHELL_PROMPT_UART="zvm_host:~#"

CONFIG_SHELL_CMD_BUFF_SIZE=1024
CONFIG_SHELL_PRINTF_BUFF_SIZE=1024
CONFIG_SHELL_STACK_SIZE=10240

#size
CONFIG_PRINTK_BUFFER_SIZE=1024
CONFIG_ISR_STACK_SIZE=40960
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192
CONFIG_PRIVILEGED_STACK_SIZE=8192

CONFIG_MAIN_STACK_SIZE=20480
CONFIG_IDLE_STACK_SIZE=8192

# 64MB heap size.
CONFIG_HEAP_MEM_POOL_SIZE=267108864

CONFIG_THREAD_NAME=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_SCHED_CPU_MASK=y
CONFIG_SCHED_CPU_MASK_PIN_ONLY=y
CONFIG_NUM_PREEMPT_PRIORITIES=15
CONFIG_TIMING_FUNCTIONS=y
CONFIG_SCHED_DEADLINE=y
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_DYNAMIC_INTERRUPTS=y

CONFIG_MAX_XLAT_TABLES=20480
CONFIG_MAX_DOMAIN_PARTITIONS=32

CONFIG_ZSHM=y

#vcpu
CONFIG_ZVM_VCPU_MULTI=y
CONFIG_VCPU_MIGRATING_INFO=n

CONFIG_ZVM_CLIENT=n
CONFIG_ZVM_MEMORY_RECORDER=n
CONFIG_ZVM_OPERATION_TEST=n

CONFIG_HEARTBEAT=n

# cpu usage
CONFIG_SCHED_THREAD_USAGE=y
CONFIG_SCHED_THREAD_USAGE_ALL=y
CONFIG_SCHED_THREAD_USAGE_ANALYSIS=y
CONFIG_THREAD_RUNTIME_STATS=y
